### ISSUE TITLE
Your list is blocking Cloudflare IPs!

### ISSUE THREAD

**Issue by mahmoud1973** [romainmarcoux/malicious-ip#1]
Hi,
Thanks for your efforts but your list contains Cloudflare IPs. If you don't add filtering for Cloudflare IP ranges then the list will be totally useless.

**Comment by romainmarcoux** [comment]
Potential explanation: some honeypots are poorly configured and they identify, as malicious traffic, traffic that is in fact return packets from their internal clients.
This is why I have done and continue to do enormous statistical and analytical work to identify these false positives.

**Comment by mahmoud1973** [comment]
> Potential explanation: some honeypots are poorly configured and they identify, as malicious traffic, traffic that is in fact return packets from their internal clients. This is why I have done and continue to do enormous statistical and analytical work to identify these false positives, which are fortunately a very small minority.

All sites using Cloudflare as a reverse proxy , all incoming traffic is routed through Cloudflare's servers. This means that all server logs will show Cloudflare IP addresses instead of the actual client IP addresses. 

That's why it's completely normal to see Cloudflare ip ranges blocked all around ip lists. It's extremely important to whitelist all Cloudflare ip ranges.
