### ISSUE TITLE
New limitations on FortiOS 7.4.4

### ISSUE THREAD

**Issue by BananaramaRenzo** [romainmarcoux/malicious-ip#3]
Hi Romain

With the new Feature Update Fortinet decided to make a new Global Limit for External Resources:
https://docs.fortinet.com/document/fortigate/7.4.0/new-features/677896/external-resource-entry-limit-enhancements-7-4-4
Now there's a Global Limit of 300k IP's. 

Are you able to create a top 300k list?

Many Thanks

**Comment by romainmarcoux** [comment]
Thank you for your suggestion.

I tested on a FortiGate-VM02 with a 256k IP file and got the following message:

"The external resource contains more entries than is supported. The A maximum amount of entries per-resource is 168928. Any entries found after the maximum has been reached will be dropped."

Do you have the same message on a physical appliance in 7.4.4?
My customers are all in 7.0 or 7.2.

**Comment by BananaramaRenzo** [comment]
Hi Romain,

No, I was able to import a 300k list without errors on my FG-60F.

Best Regards

**Comment by romainmarcoux** [comment]
New files full-300k-a*.txt added with the malicious IPs split in 300k IP files.

Thank you for helping to improve my project.
