### ISSUE TITLE
ip ban not on sources directory

### ISSUE THREAD

**Issue by PHB-fra** [romainmarcoux/malicious-ip#4]
Hi romain,

this ip 92.182.103.132 is on your file ( https://github.com/romainmarcoux/malicious-ip/blob/main/malicious-ip-by-country/full-fr-aa.txt ) 28/08/24 at 14h44 UTC+1

but a can't find it on your source : https://github.com/romainmarcoux/malicious-ip/tree/main/sources 

Why this ip is on your list without source ? 

Best regards,

**Comment by PHB-fra** [comment]
Owner of this IP is zaacom (compagny SEO Agency with botnet/crawlers).

**Comment by romainmarcoux** [comment]
Digging deeper, I see that the IP address is considered malicious on app[.]crowdsec[.]net/cti/92.182.103.132
I have no problem whitelisting the IP address but I have no information on this IP address:
- The reverse DNS does not indicate any link with the Zaacom company.
- No mention of this IP address on the Zaacom website and no mention on Google.
Do you have any proof that the IP address belongs to Zaacom?

**Comment by PHB-fra** [comment]
hi romain,

I understand your point of view and you are right. It is up to them to make the necessary effort to not get blacklisted and to behave ethically.

just in evolution on the sources directory it is possible to have the "super-romain-filter.txt" file with what you have blacklisted in order to be compliant with the full-* files ?

**Comment by romainmarcoux** [comment]
This is a very good idea.
I just added the source "sekio-a*.txt' (my company name). I updated the list of sources in the README.
If you know someone at Zaacom, you can tell them to contact me so that I can authenticate their IP addresses and whitelist them.
Thank you for helping to improve the project.

**Comment by romainmarcoux** [comment]
A person from Zaacom contacted me. I whitelisted the IP address.
