### ISSUE TITLE
False positive 35.186.224.24

### ISSUE THREAD

**Issue by hmes98318** [romainmarcoux/malicious-ip#6]
The IP address `35.186.224.24` is associated with the Spotify API, which causes the Spotify Windows client to fail to launch properly.  

![spotify-ip](https://github.com/user-attachments/assets/1359beab-85af-479a-9974-59213a8002a4)

(full-aa.txt)

**Comment by romainmarcoux** [comment]
Hello,
Thanks for your feedback, she will be whitelisted.
However, are you using the list for inbound or outbound traffic?
The list is designed to block inbound malicious traffic.

For outbound malicious traffic, I have another list:
https://github.com/romainmarcoux/malicious-outgoing-ip

**Comment by romainmarcoux** [comment]
You're welcome.
As a Spotify user, do you have access to a list of IP addresses used by Spotify in order to whitelist them?
I can't find a public list.

**Comment by hmes98318** [comment]
Unfortunately, I don't have the ip list.

**Comment by romainmarcoux** [comment]
That's what it seemed to me. Complicated to whitelist a service that does not make its public IPs available...
